name: Build and Release Go Project

on:
  push:
    tags:
      - "v*" # Triggers on version tags like v1.0, v2.0.1, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23" # Use the appropriate Go version

      - name: Build the Go binary
        run: |
          go mod download
          go build -o app main.go

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: app
          asset_name: app
          asset_content_type: application/octet-stream
