name: Build and Release Go Project

on: [push] 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23" # Use the appropriate Go version

      - name: Build the Go binary
        run: go build -o app main.go

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app